### ISSUE TITLE
has the API changed?

### ISSUE THREAD

**Issue by jvo203** [fluffysquirrels/rt-graph-rs#1]
Am following the simple example but keep getting an error:

error[E0425]: cannot find function `build_ui` in this scope
  --> src/main.rs:79:9
   |
79 |         build_ui(app);
   |         ^^^^^^^^ not found in this scope

Cargo.toml contains

```
gdk = "*"
gio = "*"
glib = "*"
gtk = "*"
rt-graph = "*"
```

and my main.rs has

```
use gio::prelude::*;
use gtk::prelude::*;
use rt_graph::{ConfigBuilder, GraphWithControls, TestDataGenerator};

use std::{
    env::args,
};
```

as well as 
```
fn main() {
    let application =
        gtk::Application::new(Some("com.github.fluffysquirrels.rt-graph.gtk-example"),
                              gio::ApplicationFlags::default())
            .expect("Application::new failed");

    application.connect_activate(|app| {
        build_ui(app);
    });

    application.run(&args().collect::<Vec<_>>());

// ...
```

Am I doing anything wrong?

**Comment by jvo203** [comment]
An embarrassment, the build_ui function was defined further down in your example... I only copied the content of the main.rs thinking build_ui was a default function from the rt-graph library. But it is in fact a user-defined function...

**Comment by fluffysquirrels** [comment]
No problem, let me know if you have any further questions!
